language: ruby
env:
  secure: vP9dkxMYLlLK+d/Km4bp7LJC29yiTV+LOHDoHrkFRfIxlqEaUwSUmSaX0B2WGhyZDQk6x2wAvpnnvtIF9C5VdRq8Tow8Dc0kq2OfiVYp4pu0ObHytkED2trLU3kdn1FSSAL0a/OWVsnp4M1pbZVryfzh8DGTpb+5yUNtK1A91GB8A80M5GK3XZTxgZeM5ghUHGEx5DB8iLvPHiTplsq6VB7L1GbRD3eNlZpiyoWBPNDAXBgAJSFTe7TBfvQyQX3DB/DXbZ5u0uz4QV2g7Af37aFfDfdyu1ZcLP7tUpuCp2qP5GER9Sz27hhbLIWj/lZmJtmGo/QZB8m11h1r7/7kqcIITWuzzctv2vvuhfoBjCsH68p3AvejzFWlxSwT6tiUOvH2oQYoo5aT0YHV2BmrkrbLBdcTxpAIWVX5Z1ByM/uOO1GtLrLSeRip9V1M5rJU6kSvxLDMy65JVtg0Ma+6WIkVM2JJgTDL4hmmt6CXiqVDZicBwU6bePsc8OXr1Khb1wb3Q48U7IC5iIOB6JaTj1OR63iFGwgzIDpOiXV+bxgNFPmKN3MgAh4CbeETjrR7W66ncblldq2AHqWH/U3FO9EaSIKZH8lWX0ocOkq3YzpceechmPZGIrrO1+5VyMrw556AeKPkrXzrAWsEs2fvxrlDKaTw6VguK1glYOG8+9M=
rvm:
- 2.1
- 2.2
- 2.3.0
- 2.4.0
cache: bundler
